name: Inventory

on:
  push:
    branches:
        - main 
  workflow_dispatch:

jobs:
  DeployingPipeline:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build Image and Push to Docker HUB"
        run: |
          docker build -t luris26/inventory-management-api-final-luris26:latest -t luris26/inventory-management-api-luris26:${{github.run_number}} .
          docker push --all-tags luris26/inventory-management-api-final-luris26

      # - name: "Build Image/Pic To Docker Hub"
      #   run: |
      #     docker build -f Dockerfile.img -t luris26/inventory-management-api-luris26-img:latest -t luris26/inventory-management-api-luris26-img:${{github.run_number}} .
      #     docker push --all-tags luris26/inventory-management-api-luris26-img

      - name: Build Kubernetes
        run: |
          export PATH=$PATH:~.nix-profile/bin:/nix/var/nix/profiles/default/bin
          export IMAGE_ID=${{ github.run_number }}

          for file in ./kubeInventory/*; do
              echo "envsubst applying to $file"
              cat $file | envsubst | kubectl apply -f -;
          done